# -*- coding: utf-8 -*-
"""pencil_sketch_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFVZ2pGdrr6Ucb0DO_MJ60NMBkz-VDwg
"""

import cv2
from google.colab.patches import cv2_imshow
image=cv2.imread("/content/nature_image.jpg")
gray_image=cv2.cvtColor(image , cv2.COLOR_BGR2GRAY)
inverted=255-gray_image
blur=cv2.GaussianBlur(inverted, (21, 21), 0)
invertedblur =255-blur
sketch=cv2.divide(gray_image, invertedblur,scale=256.0)
cv2.imwrite("sketch_image.png" , sketch)
cv2_imshow(sketch)

import cv2
from google.colab.patches import cv2_imshow

# Read the image
image = cv2.imread("/content/nature_image.jpg")

# Convert to grayscale
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Invert the grayscale image
inverted = 255 - gray_image

# Apply Gaussian Blur
blur = cv2.GaussianBlur(inverted, (21, 21), 0)

# Invert the blurred image
invertedblur = 255 - blur

# Create the sketch image by dividing the grayscale image by the inverted blurred image
sketch = cv2.divide(gray_image, invertedblur, scale=256.0)

# Save the sketch image
cv2.imwrite("sketch_image.png", sketch)

# Display the sketch image
cv2_imshow(sketch)